# Database Configuration
db.host=localhost
db.port=5432
db.name=transaction_fraud
db.user=postgres(update to add yours)
db.password=YOUR_PASSWORD_HERE

# Redis Configuration
redis.uri=redis://localhost:6379